# pre-commit package installation is necessary to use pre-commit.
# $ pip install pre-commit
# $ pre-commit install

default_language_version:
  python: python3

repos:
  # Args are based on setup.cfg.
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [
            "--max-line-length=99",
            "--ignore=E203,E704,W503",
            "--statistics",
        ]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

