name: openml

on:
  schedule:
    - cron: '0 15 * * *'
  pull_request:
    paths:
      - 'openml/**'
      - '.github/workflows/openml.yml'

jobs:
  examples:
    if: (github.event_name == 'schedule' && github.repository == 'optuna/optuna-examples') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO(c-bata): Add Python 3.9 here after fixing https://github.com/optuna/optuna-examples/issues/307
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
    - name: setup-python${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install (Python)
      run: |
        python -m pip install --upgrade pip
        pip install --progress-bar off -U setuptools
        pip install git+https://github.com/optuna/optuna.git
        python -c 'import optuna'
        pip install git+https://github.com/optuna/optuna-integration.git
        python -c 'import optuna_integration'

        pip install -r openml/requirements.txt
    - name: Run examples
      run: |
        python openml/openml_simple.py
      env:
        OMP_NUM_THREADS: 1
