name: rl

on:
  schedule:
    - cron: '0 15 * * *'
  pull_request:
    paths:
      - 'rl/**'
      - '.github/workflows/rl.yml'

jobs:
  examples:
    if: (github.event_name == 'schedule' && github.repository == 'optuna/optuna-examples') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: setup-python${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install (Python)
      run: |
        python -m pip install --upgrade pip
        #TODO(nzw0301): Remove the following version constraint after resolving sb3 supports gymnasium https://github.com/DLR-RM/stable-baselines3/pull/780
        pip install --progress-bar off -U setuptools==65.5.0
        pip install git+https://github.com/optuna/optuna.git
        python -c 'import optuna'

        pip install -r rl/requirements.txt
    - name: Run examples
      run: |
        python rl/sb3_simple.py
      env:
        OMP_NUM_THREADS: 1
